// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCubPAQrzus2o7L5ur2PQnqWUwcph8M4Ao',
    appId: '1:332816369758:web:40d4a9dbdeb17bcaf7cccf',
    messagingSenderId: '332816369758',
    projectId: 'chat-8b5cd',
    authDomain: 'chat-8b5cd.firebaseapp.com',
    storageBucket: 'chat-8b5cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2lSvoXDSbngwpmoTd7IvR-F-h6OOMYs',
    appId: '1:332816369758:android:be3e6a13586db6f8f7cccf',
    messagingSenderId: '332816369758',
    projectId: 'chat-8b5cd',
    storageBucket: 'chat-8b5cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEmBfp3wdfvo4cD85dyR2S75-s_k43T0',
    appId: '1:332816369758:ios:eb704b3be13de165f7cccf',
    messagingSenderId: '332816369758',
    projectId: 'chat-8b5cd',
    storageBucket: 'chat-8b5cd.appspot.com',
    iosBundleId: 'com.example.randomChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEmBfp3wdfvo4cD85dyR2S75-s_k43T0',
    appId: '1:332816369758:ios:cad6aa3bce86c527f7cccf',
    messagingSenderId: '332816369758',
    projectId: 'chat-8b5cd',
    storageBucket: 'chat-8b5cd.appspot.com',
    iosBundleId: 'com.example.randomChat.RunnerTests',
  );
}
